on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: tachiba/shopify-theme-kit-action@master
        with:
          # Command
          shopify-command: version
          # Flags
          shopify-flags: -p=${{ secrets.SHOPIFY_PASSWORD }} -s=${{ secrets.SHOPIFY_STORE_URL }} -t=${{ secrets.SHOPIFY_THEME_ID }}
